name: choco_bliss
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
    
  flutter_svg: ^2.0.7
  flutter_form_builder: ^9.1.0
  dio: ^5.3.2
  go_router: ^13.2.0
  image_picker: ^1.0.4
  flutter_rating_stars: ^1.0.3+4
  smooth_page_indicator: ^1.1.0
  get_storage: ^2.1.1
  path_provider: ^2.0.5
  websafe_svg: ^3.0.1+1
  google_fonts: ^6.1.0
  http: ^1.0.0
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  persistent_shopping_cart: ^0.0.7
  url_launcher: ^6.3.1
  mailto: ^2.0.0
  fluttertoast: ^8.2.8




dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 300

        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 400

        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 300



